name: Check JavaScript Syntax

on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies in client directory
        working-directory: ./client
        run: |
          npm install
          npm install eslint eslint-plugin-react

      - name: Install dependencies in server directory
        working-directory: ./server
        run: |
          npm install
          npm install eslint

      - name: Run linter on client directory
        working-directory: ./client
        run: npx eslint .

      - name: Run linter on server directory
        working-directory: ./server
        run: npx eslint .
